language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm

install:
  - npm install
  - npm install hexo-deployer-git --save
branches:
  only:
    - main # build master branch only
script:
    # - git clone https://github.com/wujun234/hexo-theme-tree.git  themes/tree
  - rm db.json
  - hexo generate --debug # generate static files
#after_script:
#- cat ./public/index.html
# - git config user.email "1921745321@qq.com"
  #- echo ${GH_TOKEN}
  # - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - hexo deploy
deploy:
  provider: pages
  token: $GH_TOKEN
  committer_from_gh: true
  keep_history: true
  skip_cleanup: true
  on:
    branch: main
  target_branch: gh-pages
  local_dir: public
