# This is a basic workflow that is manually triggered

name: Data refresh workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  #workflow_dispatch:
    # Inputs the workflow accepts.
    #inputs:
      #commit:
        # Friendly description to be shown in the UI instead of 'name'
        #description: 'commit message'
        # Default value if no value is explicitly provided
        #default: 'update changes by github actions workflow'
        # Input has to be provided for the workflow to run
        #required: true
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  updatedata:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: github-pages
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Check out repository
      uses: actions/checkout@v2
    - name: install requirements
      run: sudo pip3 install httpie jinja2 selenium
    - name: download web driver
      run: |
        wget -O geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-linux64.tar.gz
        sudo tar -xvf geckodriver.tar.gz -C /usr/local/bin/  
    - name: update data
      run: python3 update_start_list.py
    - name: Commit files
      run: |
        git config --local user.email "1921745321@qq.com"
        git config --local user.name "Ximinhan"
        git commit -m "update changes by github actions workflow" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        branch: main   
  
  build:
    needs: updatedata
    runs-on: ubuntu-latest
    environment: github-pages
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    strategy:
      matrix:
        node-version: [10.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: install hexo
      run: |
        npm install
        npm install -g hexo-cli
        npm install hexo-deployer-git --save
        npm install hexo-tag-echarts3 --save
    - name: generate files
      run: hexo generate --debug
    - name: deploy    
      run: hexo deploy

